/order/info:
  post:
    ...
    requestBody:
      content:
        application/x-www-form-urlencoded:
          schema:
            properties:
              code:
                type: string
                example: "6596E8B189"
              user:
                type: string
                example: "greenai@greencigar.bg"
              pass:
                type: string
                example: "123qwe"
            required:
              - code
              - user
              - pass
    security: []  # Remove basicAuth
