openapi: 3.0.0
info:
  title: GreenCigar API
  version: 1.0.0
  description: Retrieves order status based on unique code
  contact:
    email: support@greencigar.bg
servers:
  - url: https://greencigar.bg/api/v1
tags:
  - name: order
    description: Operations about orders
paths:
  /order/info:
    post:
      tags:
        - order
      summary: Retrieve order status by unique code
      operationId: findOrderByCode
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                code:
                  type: string
                  example: "6596E8B189"
                  description: Unique order code
              required:
                - code
      security:
        - basicAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  uniqueNumber:
                    type: string
                    example: "6596E8B189"
                  statusTxt:
                    type: string
                    example: "Завършена"
                required:
                  - uniqueNumber
                  - statusTxt
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        code:
          type: string
        messages:
          type: string
      example:
        error: "Bad Request"
        code: "400"
        messages: "Bad syntax or generic error"
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Basic HTTP authentication with username and password
