openapi: 3.0.0
info:
  title: Greencigar API
  description: API schema for Greencigar
  version: 1.0.0
servers:
  - url: https://www.greencigar.bg/api/v1
    description: Production server
paths:
  /orders:
    get:
      summary: Retrieve a list of orders
      description: Fetches a list of orders with optional filters.
      parameters:
        - in: query
          name: status
          schema:
            type: string
          description: Filter orders by status.
        - in: query
          name: customer_id
          schema:
            type: integer
          description: Filter orders by customer ID.
      security:
        - BasicAuth: []  # Ensures Basic Auth is used
      responses:
        '200':
          description: A list of orders.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '401':
          description: Unauthorized. Invalid username or password.
    post:
      summary: Create a new order
      description: Submits a new order to the system.
      security:
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewOrder'
      responses:
        '201':
          description: Order created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Bad request. Invalid input parameters.
        '401':
          description: Unauthorized. Invalid username or password.
  /orders/{order_id}:
    get:
      summary: Retrieve a specific order
      description: Fetches details of a specific order by its ID.
      security:
        - BasicAuth: []
      parameters:
        - in: path
          name: order_id
          required: true
          schema:
            type: integer
          description: The ID of the order to retrieve.
      responses:
        '200':
          description: Order details retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found.
        '401':
          description: Unauthorized. Invalid username or password.
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the order.
        customer_id:
          type: integer
          description: ID of the customer who placed the order.
        status:
          type: string
          description: Current status of the order.
        total_amount:
          type: number
          format: float
          description: Total amount for the order.
        created_at:
          type: string
          format: date-time
          description: Timestamp when the order was created.
    NewOrder:
      type: object
      properties:
        customer_id:
          type: integer
          description: ID of the customer placing the order.
        items:
          type: array
          items:
            type: object
            properties:
              product_id:
                type: integer
              quantity:
                type: integer
              price:
                type: number
                format: float
        shipping_address:
          type: string
          description: Shipping address for the order.
