openapi: 3.0.0
info:
  title: GreenCigar API
  version: 1.0.0
servers:
  - url: https://greencigar.bg/api/v1
paths:
  /order/info:
    post:
      summary: Get order details
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: Order unique number (e.g., 6596E8B189)
                Id:
                  type: string
                  description: Order ID (e.g., 0056803)
              anyOf:
                - required: [code]
                - required: [Id]
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: string
                    example: "0056803"
                  uniqueNumber:
                    type: string
                    example: "6596E8B189"
                  orderDate:
                    type: string
                    format: date-time
                    example: "2025-04-01 10:32:08"
                  shipmentCost:
                    type: string
                    example: "0.00"
                  total:
                    type: string
                    example: "133.41"
                  sh_name:
                    type: string
                    example: "Peter"
                  paid:
                    type: string
                    enum: ["0", "1"]
                    example: "1"
                  status:
                    type: string
                    example: "12"
                    description: Numeric status ID
                  statusTxt:
                    type: string
                    example: "Завършена"
                    description: Human-readable order status
                  shippingName:
                    type: string
                    example: "Доставка до адрес със Спиди "
                required:
                  - Id
                  - uniqueNumber
                  - statusTxt
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
  /order/statusesList:
    post:
      summary: List of all possible order statuses
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  properties:
                    Id:
                      type: number
                    status:
                      type: string
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
  /order/shippingMethodsList:
    post:
      summary: List shipping methods
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                zoneId:
                  type: number
                  description: The ID of the zone
              required:
                - zoneId
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  properties:
                    Id:
                      type: string
                    zoneId:
                      type: string
                    name:
                      type: string
                    calcMethod:
                      type: string
        '401':
          description: Unauthorized
  /product/info:
    post:
      summary: Get information about product
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                Id:
                  type: number
                  description: Product's unique ID
              required:
                - Id
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: string
                  parentId:
                    type: number
                  name:
                    type: string
                  price:
                    type: string
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
  /product/infoVariants:
    post:
      summary: Get information about product with all variants
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                Id:
                  type: number
                  description: Product's unique ID
              required:
                - Id
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  variantInfo:
                    type: array
                    items:
                      type: object
                      description: Detailed information about product's variant
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
