openapi: 3.0.0
info:
  title: GreenCigar API
  description: API schema for retrieving order details by code and product information.
  version: 1.0.0
servers:
  - url: https://www.greencigar.bg/api/v1
    description: Production server
paths:
  /order/info:
    post:
      summary: Get order details by code
      description: Retrieve information about an order using the unique order code.
      security:
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: The unique order code.
              required:
                - code
      responses:
        '200':
          description: Successful response with order details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: string
                    description: Internal ID of the order.
                  uniqueNumber:
                    type: string
                    description: The unique order code.
                  orderDate:
                    type: string
                    format: date-time
                    description: Date when the order was placed.
                  shipmentCost:
                    type: string
                    description: Shipping cost.
                  total:
                    type: string
                    description: Total cost of the order.
                  sh_name:
                    type: string
                    description: Shipping method name.
                  paid:
                    type: string
                    enum: ["0", "1"]
                    description: Payment status (0 = unpaid, 1 = paid).
                  statusTxt:
                    type: string
                    description: Status description of the order.
                  loadingNum:
                    type: string
                    description: Loading number for tracking.
                  statusID:
                    type: number
                    description: Status ID (matches /order/statusesList).
        '400':
          description: Bad Request - Invalid or missing order code.
        '401':
          description: Unauthorized - Invalid credentials.
  /product/info:
    post:
      summary: Get product details
      description: Retrieve information about a specific product.
      security:
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                Id:
                  type: number
                  description: The unique product ID.
              required:
                - Id
      responses:
        '200':
          description: Successful response with product details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: string
                    description: Product unique identifier.
                  parentId:
                    type: number
                    description: Parent category ID.
                  name:
                    type: string
                    description: Product name.
                  price:
                    type: string
                    description: Product price.
        '400':
          description: Bad Request - Invalid or missing product ID.
        '401':
          description: Unauthorized - Invalid credentials.
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
