openapi: 3.0.0
info:
  title: GreenCigar API
  version: 1.0.0
servers:
  - url: https://greencigar.bg/api/v1
paths:
  /order/info:
    post:
      summary: Get order details
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: Order unique number (either code or Id required)
                Id:
                  type: integer
                  description: Order ID (either code or Id required)
                user:
                  type: string
                  description: API login
                pass:
                  type: string
                  description: API password
              required:
                - user
                - pass
              anyOf:
                - required: [code]
                - required: [Id]
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: string
                  uniqueNumber:
                    type: string
                  orderDate:
                    type: string
                    format: date-time
                  shipmentCost:
                    type: string
                  total:
                    type: string
                  sh_name:
                    type: string
                  paid:
                    type: string
                    enum: ["0", "1"]
                  statusTxt:
                    type: string
                  loadingNum:
                    type: string
                    description: Loading number for that order
                  statusID:
                    type: number
                    description: Status ID. Existing in /order/statusesList status ID
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
  /order/statusesList:
    post:
      summary: List of all possible order statuses
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                user:
                  type: string
                  description: API login
                pass:
                  type: string
                  description: API password
              required:
                - user
                - pass
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  properties:
                    Id:
                      type: number
                    status:
                      type: string
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
  /order/shippingMethodsList:
    post:
      summary: List shipping methods
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                zoneId:
                  type: number
                  description: The ID of the zone
                user:
                  type: string
                  description: API login
                pass:
                  type: string
                  description: API password
              required:
                - user
                - pass
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  properties:
                    Id:
                      type: string
                    zoneId:
                      type: string
                    name:
                      type: string
                    calcMethod:
                      type: string
        '401':
          description: Unauthorized
  /product/info:
    post:
      summary: Get information about product
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                Id:
                  type: number
                  description: Product's unique ID
                user:
                  type: string
                  description: API login
                pass:
                  type: string
                  description: API password
              required:
                - Id
                - user
                - pass
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: string
                  parentId:
                    type: number
                  name:
                    type: string
                  price:
                    type: string
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
  /product/infoVariants:
    post:
      summary: Get information about product with all variants
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                Id:
                  type: number
                  description: Product's unique ID
                user:
                  type: string
                  description: API login
                pass:
                  type: string
                  description: API password
              required:
                - Id
                - user
                - pass
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  variantInfo:
                    type: array
                    items:
                      type: object
                      description: Detailed information about product's variant
        '401':
          description: Unauthorized
        '400':
          description: Bad Request