openapi: 3.0.0
info:
  title: GreenCigar API
  version: 1.0.0
servers:
  - url: https://greencigar.bg/api/v1
paths:
  /order/info:
post:
    summary: Test endpoint
    operationId: testAccess
    requestBody:
      required: true
      content:
        application/x-www-form-urlencoded:
          schema:
            type: object
            properties:
              code:
                type: string
                example: "6596E8B189"
            required:
              - code
    responses:
      '200':
        description: Test response
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: "Test successful"
